name: Publish PyPI

on:
  workflow_dispatch:

jobs:
  build:
    name: Build package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.12"

      - name: Upgrade packaging tooling
        run: python -m pip install --upgrade pip "setuptools>=83.0.0" wheel

      - name: Install build tooling
        run: python -m pip install build twine

      - name: Build package
        run: python -m build

      - name: Check package metadata
        run: python -m twine check dist/*

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/*

  publish:
    name: Publish package to PyPI
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/esaj-datajud
    permissions:
      id-token: write

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v6
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
